### ISSUE TITLE
Pull Requests

### ISSUE THREAD

**Issue by fishme** [ccoenraets/forcejs#30]
Hi @ccoenraets 

My [fork](https://github.com/fishme/forcejs) includes also a lot of new features and bugfix (waiting since February). If u have a look on the PR list, you will also find a lot others. It could be very good for the community to continue with this lib. Also the issue #29 from @ChuckJonas  is very important regarding Angular2 and Typescript in general. 

If you have no time to do it. I could also take over your repo and maintain it.

Best regards,

fishme

**Comment by ChuckJonas** [comment]
nice work!

I gave up and instead just wrote a typescript client ([ts-force](https://www.npmjs.com/package/ts-force)) that uses code generation to create interfaces for all your sObjects.   It's still in it's infancy, but stable enough that I've been using it client projects.   I have some awesome features/refactors planned, if I ever find the time to get around to it.

**Comment by ccoenraets** [comment]
@fishme @ChuckJonas Thank you for your contribution and sorry for the delay. I merged the PR. Adding support for the Lightning Container Component today and will publish new version to npm after that. Thanks again.
Christophe

**Comment by ccoenraets** [comment]
Published version 2.2.1 to npm

**Comment by fishme** [comment]
thanks @ccoenraets
